apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "pool"
  namespace: kube-system
spec:
  blocks:
    #- cidr: "10.3.3.0/24"
  - start: "10.3.3.50"
    stop: "10.3.3.120"
