replicaCount: 1
revisionHistoryLimit: 4

image:
  repository: ghcr.io/external-secrets/external-secrets
  pullPolicy: IfNotPresent

installCRDs: true

crds:
  createClusterExternalSecret: true
  createClusterSecretStore: true
  createPushSecret: true
  conversion:
    enabled: true
processClusterExternalSecret: true
processClusterStore: true
processPushSecret: true
createOperator: true


service:
  ipFamilyPolicy: ""
  # -- Sets the families that should be supported and the order in which they should be applied to ClusterIP as well. Can be IPv4 and/or IPv6.
  ipFamilies: []

serviceAccount:
  create: true
  automount: true
rbac:
  create: true
  servicebindings:
    create: true

resources:
    requests:
      cpu: 10m
      memory: 32Mi

serviceMonitor:
  enabled: true
  namespace: "external-secrets"
  interval: 15s
  scrapeTimeout: 30s

webhook:
  create: true

  certManager:
    addInjectorAnnotations: true
    cert:
      create: true
      issuerRef:
        group: cert-manager.io
        kind: "Issuer"
        name: "my-issuer"
      duration: "8760h"

certController:
  create: true
  requeueInterval: "5m"
  replicaCount: 1
  log:
    level: info
    timeEncoding: epoch
  revisionHistoryLimit: 4

  image:
    repository: ghcr.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent
  rbac:
    create: true
  serviceAccount:
    create: true
    automount: true
