- name: Install k3s on primary control plane
  become: true
  gather_facts: true
  hosts: server
  tasks:
    - name: k3s server
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.31.1+k3s1" INSTALL_K3S_EXEC="server" sh -s - \
        --cluster-init \
        --disable=traefik,servicelb,metrics-server \
        --disable-kube-proxy \
        --flannel-backend=none \
        --disable-network-policy \
        --secrets-encryption \
        --kube-apiserver-arg='audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log' \
        --kube-apiserver-arg='audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml' \
        --token {{ token }} \
        --write-kubeconfig-mode=644

- name: Install k3s on secondary control plane
  become: true
  gather_facts: true
  hosts: server-1
  tasks:
     - name: k3s server
       shell: |
         sleep 10 && curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.31.1+k3s1" INSTALL_K3S_EXEC="server" sh -s - \
         --server https://10.3.3.40:6443 \
         --disable=traefik,servicelb,metrics-server \
         --disable-kube-proxy \
         --secrets-encryption \
         --kube-apiserver-arg='audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log' \
         --kube-apiserver-arg='audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml' \
         --flannel-backend=none \
         --disable-network-policy \
         --token '{{ token }}' \
         --write-kubeconfig-mode=644


- name: Install k3s on nodes
  become: true
  gather_facts: true
  hosts: agent
  tasks:
    - name: k3 agents
      shell: |
        sleep 20 && curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.31.1+k3s1" \
        K3S_URL=https://10.3.3.40:6443 \
        K3S_TOKEN='{{ token }}' sh -s - \
        --node-label='worker=node'


